### PR TITLE
virtualenv-script.py does not exist

### PR DESCRIPTION
**Pull request by thebjorn**
I've combined a number of other branches, but the most pressing one is the virtualenv.exe vs virtualenv-script.py change.

### CODE REVIEW

**Comment by utek** [comment]
Will this be merged and deployed on PyPI?

**Comment by thebjorn** [comment]
This was one of my first pull-requests, so it's not particularly easy for the maintainer to merge, however I don't know if that matters since there hasn't been any activity for over a year on this project... You can always pip install from our repo (https://github.com/datakortet/virtualenvwrapper-win) using option 3 from http://www.reddit.com/r/Python/comments/2crput/how_to_install_with_pip_directly_from_github/  (we're using this package daily, and I try to steal any progress made on other branches..)

**Comment by utek** [comment]
Thanks. I know I can install from repo. I just would like to have it in PyPI.
(I've fixed the problem in my local clone of virtualenv wrapper, and just wanted to check id anyone fixed it first that's how I found this PR) :) Did you thought about putting your fork on PyPI?

**Comment by piotr-dobrogost** [comment]
> Did you thought about putting your fork on PyPI?

I think it would be much better to ask current maintainer @davidmarble if someone who's willing to merge these patches could obtain access to this repo. I know I once got access (still has) but as I no longer use Windows I don't want to be involved in merging these patches.

**Comment by utek** [comment]
That's even better idea :) I'll contact @davidmarble

**Comment by davidmarble** [comment]
Any of you interested in taking over the lead of this project? I've been on a Mac for the past couple years doing app development and just haven't had the motivation to fix/update virtualenvwrapper-win. Happy to have a new contributor!

**Comment by utek** [comment]
I can take it unless @thebjorn want it (as he already merging other forks into his).

**Comment by davidmarble** [comment]
@utek and @thebjorn It's a rather low-traffic repo; I'll just be happy to have one or two other coders who care enough to occasionally answer an issue or merge a pull request. Mind emailing me (username at gmail) and let's work out access to pypi as well?

**Pull request merged**
