### PR TITLE
Fix a bug that user can not delete the isolated env on win10

### PR DESCRIPTION
**Pull request by Liuyang-Z**

### CODE REVIEW

**Comment by thebjorn** [comment]
Does this relate to an open issue?

**Comment by Liuyang-Z** [comment]
I met the issue #77  the same problem. The cmd consol print the following code when I try deleting the isolated env. So, I fix this problem.

```
C:\Users\chuan>workon

Pass a name to activate one of the following virtualenvs:
==============================================================================
flask
scrapy
test  <--- delete 

C:\Users\chuan>rmvirtualenv test
The directory is not empty.

    Deleted C:\Users\chuan\Envs\test

C:\Users\chuan>workon

Pass a name to activate one of the following virtualenvs:
==============================================================================
flask
scrapy
test <-- still here

```

**Comment by thebjorn** [comment]
This isn't related to #70 (which is an unspecified "doesn't work", and is in regards to `mkvirtualenv` -- not `rmvirtualenv`).

I've created issue #78.

**Comment by thebjorn** [comment]
This is already fixed in 8a491f025dd3404ad66bbc1b8c2a46c6cfb9be04.

**Pull request closed without merging**
